### ISSUE TITLE
pupa_settings, can't find db

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/opencivicdata#11]
So I ran all the steps in the README, including bringing up the db virtual machine.

```
> cd repos/scrapers-us-municipal
> pupa update chicago
no pupa_settings on path, using defaults
chicago (scrape, import, report)
  people: {}
Not checking sessions...
...
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/psycopg2-2.6-py3.4-linux-x86_64.egg/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  database "opencivicdata" does not exist
```

Is there an environmental variable, or something I need to set.?

**Comment by rshorey** [comment]
try this:

DATABASE_URL=postgis://opencivicdata:test@10.42.2.101/opencivicdata

**Comment by fgregg** [comment]
That got me a little further, now I'm getting

```
Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "pupa_runplan" does not exist
LINE 1: INSERT INTO "pupa_runplan" ("jurisdiction_id", "success") VA...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/bin/pupa", line 9, in <module>
    load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
  File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/commands/update.py", line 249, in handle
    save_report(report, juris.jurisdiction_id)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/commands/update.py", line 58, in save_report
    plan = RunPlan.objects.create(jurisdiction_id=jurisdiction, success=report['success'])
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "pupa_runplan" does not exist
LINE 1: INSERT INTO "pupa_runplan" ("jurisdiction_id", "success") VA...
```                    ^

**Comment by paultag** [comment]
Init the db

`pupa dbinit us`

On Thu, May 21, 2015 at 10:49 AM, Forest Gregg <notifications@github.com>
wrote:

> That got me a little further, now I'm getting
>
> Traceback (most recent call last):
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
> psycopg2.ProgrammingError: relation "pupa_runplan" does not exist
> LINE 1: INSERT INTO "pupa_runplan" ("jurisdiction_id", "success") VA...
>                     ^
>
>
> The above exception was the direct cause of the following exception:
>
> Traceback (most recent call last):
>   File "/home/fgregg/public/opencivicdata/.env/bin/pupa", line 9, in <module>
>     load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
>   File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/__main__.py", line 71, in main
>     subcommands[args.subcommand].handle(args, other)
>   File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/commands/update.py", line 249, in handle
>     save_report(report, juris.jurisdiction_id)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
>     return func(*args, **kwargs)
>   File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/commands/update.py", line 58, in save_report
>     plan = RunPlan.objects.create(jurisdiction_id=jurisdiction, success=report['success'])
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
>     force_update=force_update, update_fields=update_fields)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
>     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
>     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
>     using=using, raw=raw)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
>     return query.get_compiler(using=using).execute_sql(return_id)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
>     raise value.with_traceback(tb)
>   File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: relation "pupa_runplan" does not exist
> LINE 1: INSERT INTO "pupa_runplan" ("jurisdiction_id", "success") VA...
> ```                    ^
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/opencivicdata/issues/11#issuecomment-104306001>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
yay! that worked!  Where should this be documented?

**Comment by paultag** [comment]
Perhaps something called QUICKSTART somewhere?

On Thu, May 21, 2015 at 10:53 AM, Forest Gregg <notifications@github.com>
wrote:

> yay! that worked! Where should this be documented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/opencivicdata/issues/11#issuecomment-104307425>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by jpmckinney** [comment]
Closing as issue resolved.

There are many documentation issues open, including #9.
